RapidAuto/RapidAuto.MVC/Models/Commande.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RapidAuto.MVC.Models
{
    public class Commande
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage = "Attention, veuillez entrer un numéro identifiant d'utilisateur !")]
        [Display(Name = "Numéro identifiant d'utilisateur")]
        public string? NumeroIdentifiantUtilisateur { get; set; }

        [Required(ErrorMessage = "Attention, ce champ est obligatoire !")]
        [Display(Name = "Id du véhicule")]
        public int IdVehicule { get; set; }
    }
}

RapidAuto/RapidAuto.MVC/Controllers/CommandeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RapidAuto.MVC.Interfaces;
using RapidAuto.MVC.Models;

namespace RapidAuto.MVC.Controllers
{
    public class CommandeController : Controller
    {
        private readonly IConfiguration _config;
        private readonly ICommandeService _commandeProxy;
        private readonly IUtilisateurService _utilisateurProxy;
        private readonly ILogger<CommandeController> _logger;
        private readonly IVehiculeService _vehiculeProxy;

        public CommandeController(IConfiguration config, ICommandeService commandeProxy, IUtilisateurService utilisateurProxy, ILogger<CommandeController> logger, IVehiculeService vehiculeProxy)
        {
            _config = config;
            _commandeProxy = commandeProxy;
            _utilisateurProxy = utilisateurProxy;
            _logger = logger;
            _vehiculeProxy = vehiculeProxy;
        }

        // GET: CommandeController
        public async Task<ActionResult> Index()
        {
            var listeDesCommandes = await _commandeProxy.ObtenirCommandes();

            return View(listeDesCommandes.ToList());
        }

        // GET: CommandeController/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _commandeProxy.ObtenirUneCommande(id);

            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // GET: CommandeController/Create
        public async Task<ActionResult> Create(int idVehicule)
        {
            ViewData["VehiculeACommander"] = await _vehiculeProxy.ObtenirUnVehicule(idVehicule);
            return View();
        }

        // POST: CommandeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Commande commande)
        {
            ViewData["VehiculeACommander"] = await _vehiculeProxy.ObtenirUnVehicule(commande.IdVehicule);
            var utilisateur = await _utilisateurProxy.ObtenirUnUtilisateurAvecNumeroIdentifiant(commande.NumeroIdentifiantUtilisateur); 

            if (utilisateur.IdentifiantUtilisateur == null) 
            {
                ModelState.AddModelError("NumeroIdentifiantUtilisateur", "Utilisateur inexistant, veuillez entrer un identifiant valide !");
                return View(commande);
            }

            if (ModelState.IsValid)
            {
                await _commandeProxy.Ajouter(commande);

                _logger.LogInformation(CustomLogEvenements.EnregistrementCommande, $"Ajout d'une commande (Id: {commande.Id})");

                var vehicule = await _vehiculeProxy.ObtenirUnVehicule(commande.IdVehicule);
                vehicule.EstDisponible = false;

                await _vehiculeProxy.Modifier(vehicule);

                return View("CommandeSucces", commande);
            }

            return View(commande);
        }

        // GET: CommandeController/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _commandeProxy.ObtenirUneCommande(id.Value);

            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // POST: CommandeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, Commande commande)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (id != commande.Id)
            {
                return NotFound();
            }

            var utilisateur = await _utilisateurProxy.ObtenirUnUtilisateurAvecNumeroIdentifiant(commande.NumeroIdentifiantUtilisateur);

            if (utilisateur.IdentifiantUtilisateur == null)
            {
                ModelState.AddModelError("NumeroIdentifiantUtilisateur", "Utilisateur inexistant, veuillez entrer un identifiant valide !");
                return View(commande);
            }

            if (ModelState.IsValid)
            {
                await _commandeProxy.Modifier(commande);
                return RedirectToAction(nameof(Index));
            }

            return View(commande);
        }

        // GET: CommandeController/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _commandeProxy.ObtenirUneCommande(id.Value);

            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // POST: CommandeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            var commande = await _commandeProxy.ObtenirUneCommande(id);

            if (commande == null)
            {
                return RedirectToAction(nameof(Index));
            }

            await _commandeProxy.Supprimer(id);

            // on remet le vehicule disponible
            var vehicule = await _vehiculeProxy.ObtenirUnVehicule(commande.IdVehicule);
            vehicule.EstDisponible = true;

            await _vehiculeProxy.Modifier(vehicule);

            return RedirectToAction(nameof(Index));
        }
    }
}

RapidAuto/RapidAuto.MVC/Controllers/VehiculeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RapidAuto.MVC.Interfaces;
using RapidAuto.MVC.Models;
using System.Linq;

namespace RapidAuto.MVC.Controllers
{
    public class VehiculeController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IVehiculeService _vehiculeProxy;
        private readonly IFichierService _fichierProxy;
        private readonly IFavorisService _favorisProxy;
        private readonly ILogger<VehiculeController> _logger;


        public VehiculeController(IConfiguration configuration, IVehiculeService vehiculeProxy, IFichierService fichierProxy, IFavorisService favorisService, ILogger<VehiculeController> logger)
        {
            _configuration = configuration;
            _vehiculeProxy = vehiculeProxy;
            _fichierProxy = fichierProxy;
            _favorisProxy = favorisService;
            _logger = logger;
        }

        // GET: VehiculeController
        public async Task<ActionResult> Index(string ordreDeTri, string searchString)
        {
            var nomConteneur = "images";
            var urlConteneur = await _fichierProxy.ObtenirUrlConteneur(nomConteneur);
            ViewBag.UrlConteneur = urlConteneur;

            ViewData["TriParPrix"] = "prix_desc";
            if (ordreDeTri == "prix_desc")
            {
                ViewData["TriParPrix"] = "prix_asc";
            }
            else if (ordreDeTri == "prix_asc")
            {
                ViewData["TriParPrix"] = "prix_desc";
            }

            var listeDeVehicules = await _vehiculeProxy.ObtenirVehicules();

            switch (ordreDeTri)
            {
                case "prix_desc":
                    listeDeVehicules = listeDeVehicules.OrderByDescending(x => x.Prix);
                    break;
                case "prix_asc":
                    listeDeVehicules = listeDeVehicules.OrderBy(x => x.Prix);
                    break;
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                listeDeVehicules = listeDeVehicules.Where(v => v.Constructeur.ToLower().Contains(searchString.ToLower())
                                                            || v.Modele.ToLower().Contains(searchString.ToLower()));

                _logger.LogInformation(CustomLogEvenements.Recherche, $"Recherche effectuée ({searchString}), sur la liste des véhicules.");
            }

            return View(listeDeVehicules.ToList());
        }

        // GET: VehiculeController/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            var nomConteneur = "images";
            var urlConteneur = await _fichierProxy.ObtenirUrlConteneur(nomConteneur);
            ViewBag.UrlConteneur = urlConteneur;

            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _vehiculeProxy.ObtenirUnVehicule(id);

            if (vehicule == null)
            {
                return NotFound();
            }

            _logger.LogInformation(CustomLogEvenements.LectureDUnVehicule, $"Affichage du véhicule (Id: {vehicule.Id})");

            return View(vehicule);
        }

        // GET: VehiculeController/Create
        public ActionResult Create()
        {
            ViewBag.TypesDeVehicule = RecupererTypesDeVehicule();

            return View();
        }

        // POST: VehiculeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Vehicule vehicule)
        {
            ViewBag.TypesDeVehicule = RecupererTypesDeVehicule();

            var images = new List<IFormFile>() { vehicule.Image1, vehicule.Image2 };

            if (ValiderExtensionFichier(vehicule.Image1.FileName) == false)
            {
                ModelState.AddModelError("Image1", "Attention, seulement les extensions jpg, jpeg et png sont supportées !");
            }

            if (ValiderExtensionFichier(vehicule.Image2.FileName) == false)
            {
                ModelState.AddModelError("Image2", "Attention, seulement les extensions jpg, jpeg et png sont supportées !");
            }

            if (vehicule.Image1 == null)
            {
                ModelState.AddModelError("Image1", "Attention, le champ est obligatoire !");
            }

            if (vehicule.Image2 == null)
            {
                ModelState.AddModelError("Image2", "Attention, le champ est obligatoire !");
            }

            if (ModelState.IsValid)
            {

                vehicule.CodeUnique = await _vehiculeProxy.ObtenirCodeUnique(vehicule.Modele);
                var imagesConverties = await _fichierProxy.ConvertirImagesEnBytes(images);

                await _fichierProxy.AjouterImages(imagesConverties, vehicule.CodeUnique);
                var nomsDesImagesDuVehicule = await _fichierProxy.ObtenirNomsImages(vehicule.CodeUnique);

                nomsDesImagesDuVehicule.Sort();

                vehicule.NomImage1 = nomsDesImagesDuVehicule[0];
                vehicule.NomImage2 = nomsDesImagesDuVehicule[1];

                await _vehiculeProxy.Ajouter(vehicule);

                _logger.LogInformation(CustomLogEvenements.EnregistrementVehicule, $"Ajout d'un véhicule (Id: {vehicule.Id})");

                return RedirectToAction(nameof(Index));
            }

            return View(vehicule);
        }

        // GET: VehiculeController/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.TypesDeVehicule = RecupererTypesDeVehicule();

            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _vehiculeProxy.ObtenirUnVehicule(id.Value);

            if (vehicule == null)
            {
                return NotFound();
            }

            return View(vehicule);
        }

        // POST: VehiculeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, Vehicule vehicule)
        {
            ViewBag.TypesDeVehicule = RecupererTypesDeVehicule();

            if (id == null)
            {
                return NotFound();
            }

            var vehiculeAvantModification = await _vehiculeProxy.ObtenirUnVehicule(vehicule.Id);

            if (vehiculeAvantModification.Modele != vehicule.Modele)
            {
                vehicule.CodeUnique = await _vehiculeProxy.ObtenirCodeUnique(vehicule.Modele);

                // Si le modèle du véhicule change, on doit modifier le nom des images avec le nouveau code unique attribué à celui-ci.
                // **** On fait ce traitement si et seulement si on n'ajoute PAS de nouvelles images ****

                if (vehicule.Image1 == null)
                {
                    vehicule.NomImage1 = await _fichierProxy.ModifierImage(new List<string>() { vehicule.NomImage1, vehicule.CodeUnique });
                }

                if (vehicule.Image2 == null)
                {
                    vehicule.NomImage2 = await _fichierProxy.ModifierImage(new List<string>() { vehicule.NomImage2, vehicule.CodeUnique });
                }
            }

            var listeNouvellesImages = new List<IFormFile>();

            if (vehicule.Image1 != null)
            {
                if (ValiderExtensionFichier(vehicule.Image1.FileName) == false)
                {
                    ModelState.AddModelError("Image1", "Attention, seulement les extensions jpg, jpeg et png sont supportées !");
                }
                else
                {
                    listeNouvellesImages.Add(vehicule.Image1);
                    // On supprime l'ancienne Image1
                    await _fichierProxy.SupprimerImage(vehicule.NomImage1);
                }
            }

            if (vehicule.Image2 != null)
            {
                if (ValiderExtensionFichier(vehicule.Image1.FileName) == false)
                {
                    ModelState.AddModelError("Image2", "Attention, seulement les extensions jpg, jpeg et png sont supportées !");
                }
                else
                {
                    listeNouvellesImages.Add(vehicule.Image2);
                    // On supprime l'ancienne Image2
                    await _fichierProxy.SupprimerImage(vehicule.NomImage2);
                }
            }

            // Pour la logique de l'enregistrement des images, on s'assure qu'on enregistre les deux.
            if (listeNouvellesImages.Count == 1)
            {
                ModelState.AddModelError("Image1", "Attention, si vous ajoutez de nouvelles images, vous devez le faire pour l'Image 1 et l'Image 2 ");
                ModelState.AddModelError("Image2", "Attention, si vous ajoutez de nouvelles images, vous devez le faire pour l'Image 1 et l'Image 2 ");
            }


            if (ModelState.IsValid)
            {
                if (listeNouvellesImages.Count > 0)
                {
                    var imagesConverties = await _fichierProxy.ConvertirImagesEnBytes(listeNouvellesImages);
                    await _fichierProxy.AjouterImages(imagesConverties, vehicule.CodeUnique);

                    var nomsDesImagesDuVehicule = await _fichierProxy.ObtenirNomsImages(vehicule.CodeUnique);

                    nomsDesImagesDuVehicule.Sort();

                    vehicule.NomImage1 = nomsDesImagesDuVehicule[0];
                    vehicule.NomImage2 = nomsDesImagesDuVehicule[1];
                }

                await _vehiculeProxy.Modifier(vehicule);

                _logger.LogInformation(CustomLogEvenements.ModificationVehicule, $"Modification d'un véhicule (Id: {vehicule.Id})");

                return RedirectToAction(nameof(Index));
            }

            return View(vehicule);
        }

        // GET: VehiculeController/Delete/5
        public async Task<ActionResult> Delete(int? id)

RapidAuto/RapidAuto.MVC/Views/Commande/CommandeSucces.cshtml
@model RapidAuto.MVC.Models.Commande

<h1>Succès</h1>

<div>
    <h4>Votre véhicule a été commandé !</h4>
</div>
<hr />
<div>
    <a asp-controller="Vehicule" asp-action="Index">Retourner à la liste des véhicules</a>
    <a asp-controller="Commande" asp-action="Index">Retourner à la liste des commandes</a>
</div>

RapidAuto/RapidAuto.MVC/Views/Commande/Create.cshtml
@model RapidAuto.MVC.Models.Commande

@{
    ViewData["Title"] = "Create";
    var vehicule = ViewData["VehiculeACommander"] as Vehicule;
}

<h1>Commander</h1>

<h4>Commande</h4>
<hr />
<div>
    <h4>Description du véhicule</h4>
    <p>@vehicule.Description</p>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroIdentifiantUtilisateur" class="control-label"></label>
                <input asp-for="NumeroIdentifiantUtilisateur" class="form-control" />
                <span asp-validation-for="NumeroIdentifiantUtilisateur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input hidden asp-for="IdVehicule" class="form-control" value="@vehicule.Id" />
                <span asp-validation-for="NumeroIdentifiantUtilisateur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Valider" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Vehicule" asp-action="Index">Retourner à la liste des véhicules</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RapidAuto/RapidAuto.MVC/Views/Commande/Delete.cshtml
@model RapidAuto.MVC.Models.Commande

@{
    ViewData["Title"] = "Delete";
}

<h1>Supprimer</h1>

<h3>Êtes-vous certain de vouloir supprimer cette commande?</h3>
<div>
    <h4>Commande</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroIdentifiantUtilisateur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroIdentifiantUtilisateur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdVehicule)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdVehicule)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retourner à la liste des commandes</a>
    </form>
</div>

RapidAuto/RapidAuto.MVC/Views/Commande/Details.cshtml
@model RapidAuto.MVC.Models.Commande

@{
    ViewData["Title"] = "Details";
}

<h1>Détails de la commande</h1>

<div>
    <h4>Commande</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroIdentifiantUtilisateur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroIdentifiantUtilisateur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdVehicule)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdVehicule)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Modifier", "Edit", new {  id = Model.Id }) |
    <a asp-action="Index">Retourner à la liste des commandes</a>
</div>

RapidAuto/RapidAuto.MVC/Views/Commande/Edit.cshtml
@model RapidAuto.MVC.Models.Commande

@{
    ViewData["Title"] = "Edit";
}

<h1>Modifier</h1>

<h4>Commande</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroIdentifiantUtilisateur" class="control-label"></label>
                <input asp-for="NumeroIdentifiantUtilisateur" class="form-control" />
                <span asp-validation-for="NumeroIdentifiantUtilisateur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input hidden asp-for="IdVehicule" class="form-control" />
                <span asp-validation-for="IdVehicule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retourner à la liste des commandes</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RapidAuto/RapidAuto.MVC/Views/Commande/Index.cshtml
@model IEnumerable<RapidAuto.MVC.Models.Commande>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des commandes</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroIdentifiantUtilisateur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdVehicule)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroIdentifiantUtilisateur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdVehicule)
            </td>
            <td>
                @Html.ActionLink("Modifier", "Edit", new {  id=item.Id }) |
                @Html.ActionLink("Afficher", "Details", new {  id=item.Id }) |
                @Html.ActionLink("Supprimer", "Delete", new {  id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>