RapidAuto/RapidAuto.MVC/Controllers/FavorisController.cs
using Microsoft.AspNetCore.Mvc;
using RapidAuto.MVC.Interfaces;
using RapidAuto.MVC.Models;

namespace RapidAuto.MVC.Controllers
{
    public class FavorisController : Controller
    {
        private readonly IFavorisService _favorisService;
        private readonly IVehiculeService _vehiculeService;

        public FavorisController(IFavorisService favorisService, IVehiculeService vehiculeService)
        {
            _favorisService = favorisService;
            _vehiculeService = vehiculeService;
        }

        // GET: FavorisController
        public async Task<ActionResult> Index()
        {
            var listeDesFavoris = await _favorisService.ObtenirFavoris();

            return View(listeDesFavoris.ToList());
        }

        // GET: FavorisController/Create
        public async Task<ActionResult> Create(int idVehicule)
        {
            var vehicule = await _vehiculeService.ObtenirUnVehicule(idVehicule);

            if (vehicule == null)
            {
                return View("Error");
            }

            return View(vehicule);
        }

        // POST: FavorisController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Vehicule vehicule)
        {
            await _favorisService.AjouterFavori(vehicule);

            return RedirectToAction(nameof(Index));
        }

        // GET: FavorisController/Delete/5
        public async Task<ActionResult> Delete(int idVehicule)
        {
            var vehiculeFavori = await _vehiculeService.ObtenirUnVehicule(idVehicule);

            if (vehiculeFavori == null)
            {
                return View("Error");
            }

            return View(vehiculeFavori);
        }

        // POST: FavorisController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Vehicule vehicule)
        {
            await _favorisService.SupprimerFavori(vehicule.Id);

            return RedirectToAction(nameof(Index));
        }

    }
}

RapidAuto/RapidAuto.MVC/Controllers/VehiculeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RapidAuto.MVC.Interfaces;
using RapidAuto.MVC.Models;
using System.Linq;

namespace RapidAuto.MVC.Controllers
{
    public class VehiculeController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IVehiculeService _vehiculeProxy;
        private readonly IFichierService _fichierProxy;
        private readonly IFavorisService _favorisProxy;
        private readonly ILogger<VehiculeController> _logger;


        public VehiculeController(IConfiguration configuration, IVehiculeService vehiculeProxy, IFichierService fichierProxy, IFavorisService favorisService, ILogger<VehiculeController> logger)
        {
            _configuration = configuration;
            _vehiculeProxy = vehiculeProxy;
            _fichierProxy = fichierProxy;
            _favorisProxy = favorisService;
            _logger = logger;
        }

        // GET: VehiculeController
        public async Task<ActionResult> Index(string ordreDeTri, string searchString)
        {
            var nomConteneur = "images";
            var urlConteneur = await _fichierProxy.ObtenirUrlConteneur(nomConteneur);
            ViewBag.UrlConteneur = urlConteneur;

            ViewData["TriParPrix"] = "prix_desc";
            if (ordreDeTri == "prix_desc")
            {
                ViewData["TriParPrix"] = "prix_asc";
            }
            else if (ordreDeTri == "prix_asc")
            {
                ViewData["TriParPrix"] = "prix_desc";
            }

            var listeDeVehicules = await _vehiculeProxy.ObtenirVehicules();

            switch (ordreDeTri)
            {
                case "prix_desc":
                    listeDeVehicules = listeDeVehicules.OrderByDescending(x => x.Prix);
                    break;
                case "prix_asc":
                    listeDeVehicules = listeDeVehicules.OrderBy(x => x.Prix);
                    break;
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                listeDeVehicules = listeDeVehicules.Where(v => v.Constructeur.ToLower().Contains(searchString.ToLower())
                                                            || v.Modele.ToLower().Contains(searchString.ToLower()));

                _logger.LogInformation(CustomLogEvenements.Recherche, $"Recherche effectuée ({searchString}), sur la liste des véhicules.");
            }

            return View(listeDeVehicules.ToList());
        }

        // GET: VehiculeController/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            var nomConteneur = "images";
            var urlConteneur = await _fichierProxy.ObtenirUrlConteneur(nomConteneur);
            ViewBag.UrlConteneur = urlConteneur;

            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _vehiculeProxy.ObtenirUnVehicule(id);

            if (vehicule == null)
            {
                return NotFound();
            }

            _logger.LogInformation(CustomLogEvenements.LectureDUnVehicule, $"Affichage du véhicule (Id: {vehicule.Id})");

            return View(vehicule);
        }

        // GET: VehiculeController/Create
        public ActionResult Create()
        {
            ViewBag.TypesDeVehicule = RecupererTypesDeVehicule();

            return View();
        }

        // POST: VehiculeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Vehicule vehicule)
        {
            ViewBag.TypesDeVehicule = RecupererTypesDeVehicule();

            var images = new List<IFormFile>() { vehicule.Image1, vehicule.Image2 };

            if (ValiderExtensionFichier(vehicule.Image1.FileName) == false)
            {
                ModelState.AddModelError("Image1", "Attention, seulement les extensions jpg, jpeg et png sont supportées !");
            }

            if (ValiderExtensionFichier(vehicule.Image2.FileName) == false)
            {
                ModelState.AddModelError("Image2", "Attention, seulement les extensions jpg, jpeg et png sont supportées !");
            }

            if (vehicule.Image1 == null)
            {
                ModelState.AddModelError("Image1", "Attention, le champ est obligatoire !");
            }

            if (vehicule.Image2 == null)
            {
                ModelState.AddModelError("Image2", "Attention, le champ est obligatoire !");
            }

            if (ModelState.IsValid)
            {

                vehicule.CodeUnique = await _vehiculeProxy.ObtenirCodeUnique(vehicule.Modele);
                var imagesConverties = await _fichierProxy.ConvertirImagesEnBytes(images);

                await _fichierProxy.AjouterImages(imagesConverties, vehicule.CodeUnique);
                var nomsDesImagesDuVehicule = await _fichierProxy.ObtenirNomsImages(vehicule.CodeUnique);

                nomsDesImagesDuVehicule.Sort();

                vehicule.NomImage1 = nomsDesImagesDuVehicule[0];
                vehicule.NomImage2 = nomsDesImagesDuVehicule[1];

                await _vehiculeProxy.Ajouter(vehicule);

                _logger.LogInformation(CustomLogEvenements.EnregistrementVehicule, $"Ajout d'un véhicule (Id: {vehicule.Id})");

                return RedirectToAction(nameof(Index));
            }

            return View(vehicule);
        }

        // GET: VehiculeController/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.TypesDeVehicule = RecupererTypesDeVehicule();

            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _vehiculeProxy.ObtenirUnVehicule(id.Value);

            if (vehicule == null)
            {
                return NotFound();
            }

            return View(vehicule);
        }

        // POST: VehiculeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, Vehicule vehicule)
        {
            ViewBag.TypesDeVehicule = RecupererTypesDeVehicule();

            if (id == null)
            {
                return NotFound();
            }

            var vehiculeAvantModification = await _vehiculeProxy.ObtenirUnVehicule(vehicule.Id);

            if (vehiculeAvantModification.Modele != vehicule.Modele)
            {
                vehicule.CodeUnique = await _vehiculeProxy.ObtenirCodeUnique(vehicule.Modele);

                // Si le modèle du véhicule change, on doit modifier le nom des images avec le nouveau code unique attribué à celui-ci.
                // **** On fait ce traitement si et seulement si on n'ajoute PAS de nouvelles images ****

                if (vehicule.Image1 == null)
                {
                    vehicule.NomImage1 = await _fichierProxy.ModifierImage(new List<string>() { vehicule.NomImage1, vehicule.CodeUnique });
                }

                if (vehicule.Image2 == null)
                {
                    vehicule.NomImage2 = await _fichierProxy.ModifierImage(new List<string>() { vehicule.NomImage2, vehicule.CodeUnique });
                }
            }

            var listeNouvellesImages = new List<IFormFile>();

            if (vehicule.Image1 != null)
            {
                if (ValiderExtensionFichier(vehicule.Image1.FileName) == false)
                {
                    ModelState.AddModelError("Image1", "Attention, seulement les extensions jpg, jpeg et png sont supportées !");
                }
                else
                {
                    listeNouvellesImages.Add(vehicule.Image1);
                    // On supprime l'ancienne Image1
                    await _fichierProxy.SupprimerImage(vehicule.NomImage1);
                }
            }

            if (vehicule.Image2 != null)
            {
                if (ValiderExtensionFichier(vehicule.Image1.FileName) == false)
                {
                    ModelState.AddModelError("Image2", "Attention, seulement les extensions jpg, jpeg et png sont supportées !");
                }
                else
                {
                    listeNouvellesImages.Add(vehicule.Image2);
                    // On supprime l'ancienne Image2
                    await _fichierProxy.SupprimerImage(vehicule.NomImage2);
                }
            }

            // Pour la logique de l'enregistrement des images, on s'assure qu'on enregistre les deux.
            if (listeNouvellesImages.Count == 1)
            {
                ModelState.AddModelError("Image1", "Attention, si vous ajoutez de nouvelles images, vous devez le faire pour l'Image 1 et l'Image 2 ");
                ModelState.AddModelError("Image2", "Attention, si vous ajoutez de nouvelles images, vous devez le faire pour l'Image 1 et l'Image 2 ");
            }


            if (ModelState.IsValid)
            {
                if (listeNouvellesImages.Count > 0)
                {
                    var imagesConverties = await _fichierProxy.ConvertirImagesEnBytes(listeNouvellesImages);
                    await _fichierProxy.AjouterImages(imagesConverties, vehicule.CodeUnique);

                    var nomsDesImagesDuVehicule = await _fichierProxy.ObtenirNomsImages(vehicule.CodeUnique);

                    nomsDesImagesDuVehicule.Sort();

                    vehicule.NomImage1 = nomsDesImagesDuVehicule[0];
                    vehicule.NomImage2 = nomsDesImagesDuVehicule[1];
                }

                await _vehiculeProxy.Modifier(vehicule);

                _logger.LogInformation(CustomLogEvenements.ModificationVehicule, $"Modification d'un véhicule (Id: {vehicule.Id})");

                return RedirectToAction(nameof(Index));
            }

            return View(vehicule);
        }

        // GET: VehiculeController/Delete/5
        public async Task<ActionResult> Delete(int? id)

RapidAuto/RapidAuto.MVC/Views/Favoris/Create.cshtml
@model RapidAuto.MVC.Models.Vehicule

@{
    ViewData["Title"] = "Create";

    //var pathImages = @"https:\\localhost:7031\";
}

<h1>Ajouter un véhicule à vos favoris</h1>

<h4>Voulez-vous ajouter ce véhicule ?</h4>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Constructeur)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Constructeur)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modele)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modele)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Annee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Annee)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TypeVehicule)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TypeVehicule)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NombreDeSieges)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NombreDeSieges)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Couleur)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Couleur)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NIV)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NIV)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstDisponible)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstDisponible)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Prix)
        </dd>
        @* <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomImage1)
        </dt>
        <dd class="col-sm-10">
            <img src="@(pathImages+Model.NomImage1)" alt="Model.NomImage1" width="300px" height="200px" title="Model.NomImage1"/> 
        </dd>*@
    </dl>

    <form asp-action="Create">
        @Html.HiddenFor(v => v.Id)
        @Html.HiddenFor(v => v.Constructeur)
        @Html.HiddenFor(v => v.Modele)
        @Html.HiddenFor(v => v.Annee)
        @Html.HiddenFor(v => v.TypeVehicule)
        @Html.HiddenFor(v => v.NombreDeSieges)
        @Html.HiddenFor(v => v.Couleur)
        @Html.HiddenFor(v => v.NIV)
        @Html.HiddenFor(v => v.NomImage1)
        @Html.HiddenFor(v => v.NomImage2)
        @Html.HiddenFor(v => v.Description)
        @Html.HiddenFor(v => v.EstDisponible)
        @Html.HiddenFor(v => v.Prix)

        <input type="submit" value="Ajouter" class="btn btn-primary" />
        <a asp-action="Index">Retour à vos favoris</a>
    </form>
</div>

RapidAuto/RapidAuto.MVC/Views/Favoris/Delete.cshtml
@model RapidAuto.MVC.Models.Vehicule

@{
    ViewData["Title"] = "Delete";

    //var pathImages = @"https:\\localhost:7031\";
}

<h1>Supprimer un véhicule de vos favoris</h1>

<h3>Êtes-vous certain de vouloir supprimer ce véhicule ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Constructeur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Constructeur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modele)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modele)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Annee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Annee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeVehicule)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeVehicule)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreDeSieges)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreDeSieges)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Couleur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Couleur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIV)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIV)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstDisponible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstDisponible)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prix)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomImage1)
        </dt>
        <dd class = "col-sm-10">
            <img src="@(pathImages+Model.NomImage1)" alt="Model.NomImage1" width="300px" height="200px" title="Model.NomImage1"/>
        </dd>*@
    </dl>

    <form asp-action="Delete">
        @Html.HiddenFor(v => v.Id)
        @Html.HiddenFor(v => v.Constructeur)
        @Html.HiddenFor(v => v.Modele)
        @Html.HiddenFor(v => v.Annee)
        @Html.HiddenFor(v => v.TypeVehicule)
        @Html.HiddenFor(v => v.NombreDeSieges)
        @Html.HiddenFor(v => v.Couleur)
        @Html.HiddenFor(v => v.NIV)
        @Html.HiddenFor(v => v.NomImage1)
        @Html.HiddenFor(v => v.NomImage2)
        @Html.HiddenFor(v => v.Description)
        @Html.HiddenFor(v => v.EstDisponible)
        @Html.HiddenFor(v => v.Prix)

        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à vos favoris</a>
    </form>
</div>

RapidAuto/RapidAuto.MVC/Views/Favoris/Index.cshtml
@model IEnumerable<RapidAuto.MVC.Models.Vehicule>

@{
    ViewData["Title"] = "Index";

    var pathImages = @"https:\\localhost:7031\";
}

<h1>Véhicules favoris</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Constructeur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modele)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Annee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeVehicule)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreDeSieges)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Couleur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NIV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstDisponible)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prix)
            </th>
            <th>
                Image
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Constructeur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modele)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Annee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeVehicule)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreDeSieges)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Couleur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NIV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstDisponible)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prix)
            </td>
            @{
                if (item.NomImage1 == null)
                {
                    <td>
                        Aucune image
                    </td>
                }
                else
                {
                    <td>
                        <img src="@(pathImages+item.NomImage1)" alt="@item.NomImage1" width="300px" height="200px" title="@item.NomImage1"/>
                    </td>
                }
            }
            <td>
                <button type="button" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("Details", "Vehicule", new { item.Id })'">Détails du véhicule</button>
                <button type="button" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("Delete", "Favoris", new { idVehicule = item.Id })'">Supprimer</button>
            </td>
        </tr>
    }
    </tbody>
</table>